# To run a command in the conda env you have to use 'shell: bash -l {0}'
# See https://github.com/marketplace/actions/setup-miniconda#important

name: Build on Ubuntu
on: [push]
jobs:
  "Build on Ubuntu":
    runs-on: ubuntu-18.04
    env:
      ISISDATA: /isisData/isis_data
      ISISTESTDATA: /isisData/isis_testData
      ISISROOT: "${{ github.workspace }}/build"
      MALLOC_CHECK_: "1"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          channels: usgs-astrogeology,conda-forge,defaults
          activate-environment: isis3

      - run: "sudo sh -c 'apt-get update && apt-get install gcc g++ ninja-build -y'"

      - run: conda install -c conda-forge python=3 findutils
      - run: conda env update -n isis3 -f environment.yml
      - run: mkdir build install
      - run: echo "$GITHUB_WORKSPACE/install/bin" >> $GITHUB_PATH

      - run: |
          cmake \
            -GNinja \
            -DJP2KFLAG=OFF \
            -DKAKADU_INCLUDE_DIR=/isisData/kakadu \
            -Dpybindings=OFF \
            -DCMAKE_BUILD_TYPE=RELEASE \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
            ../isis
        shell: bash -l {0}
        working-directory: "${{ env.ISISROOT }}"

      - run: ninja -j$(grep processor /proc/cpuinfo | wc -l) install
        shell: bash -l {0}
        working-directory: "${{ env.ISISROOT }}"
